keys:
  - &users
    - &Coolio age1w33vqk2vvhxegtlmypv29cdpcghgqdz5zzzw408qmwd0p0qnacgqhpx9al
  - &hosts
    - &hydrus age187r379mfp8x86mzdj80uzq0unm75r48h9j7dwup5xlr39frqkd7sfcgnkx
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *Coolio
          - *hydrus
